### ISSUE TITLE
Clean the root?

### ISSUE THREAD

**Issue by HerHde** [okfde/2013.archiv.codefor.de#302]
It's a pain to look at the root, how about...
1. move oklabs into an own folder? E.g. `/oklabs/paderborn/index.html`
2. put all Pages into an subfolder? Maybe altering it from `/pagename/index.html` to `/pages/pagename.html`
3. move the Apple icons into a subfolder of img?
4. put all assets together? E.g. `/assets/css/...` and `/assets/img/...`

**Comment by gitviola** [comment]
@HerHde I also prefer a clean root directory but since we use jekyll we should stick with the jekyll conventions (4). If we put each lab into a `oklabs` directory the url will change as well `codefor.de/oklabs/ruhrgebiet` which means that we will have tons of dead links (SEO ranking) unless we create a 301 redirection for each lab (1, 2).

3: I think all files that currently are in the root directory need to be there (Apple devices expect the icons to be in the root, don't they?)

**Comment by jfilter** [comment]
Yes, the folder structure is not great. But we should under no circumstances change the URLs. So let's leave it as it is. ;)

If you really want to improve the website and it's setup, I guess you would re-write it with <https://gohugo.io/>. But I also don't see any real value of spending so much time on it.

Since there hasn't a lot of activity in this issue, I will close it.
